//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Superkatten.Katministratie.Contract.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KatministratieApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KatministratieApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Superkatten.Katministratie.Contract.Language.KatministratieApp", typeof(KatministratieApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volwassen.
        /// </summary>
        public static string AgeCategoryAdult {
            get {
                return ResourceManager.GetString("AgeCategoryAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puber.
        /// </summary>
        public static string AgeCategoryJuvenile {
            get {
                return ResourceManager.GetString("AgeCategoryJuvenile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitten.
        /// </summary>
        public static string AgeCategoryKitten {
            get {
                return ResourceManager.GetString("AgeCategoryKitten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grote Ren.
        /// </summary>
        public static string CatAreaBigEnclosure {
            get {
                return ResourceManager.GetString("CatAreaBigEnclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziekenboeg.
        /// </summary>
        public static string CatAreaInfirmary {
            get {
                return ResourceManager.GetString("CatAreaInfirmary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarantine.
        /// </summary>
        public static string CatAreaQuarantine {
            get {
                return ResourceManager.GetString("CatAreaQuarantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweede Kamer.
        /// </summary>
        public static string CatAreaRoom2 {
            get {
                return ResourceManager.GetString("CatAreaRoom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleine Ren.
        /// </summary>
        public static string CatAreaSmallEnclosure {
            get {
                return ResourceManager.GetString("CatAreaSmallEnclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schuw.
        /// </summary>
        public static string CatBehaviourShy {
            get {
                return ResourceManager.GetString("CatBehaviourShy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociaal.
        /// </summary>
        public static string CatBehaviourSocial {
            get {
                return ResourceManager.GetString("CatBehaviourSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onbekend.
        /// </summary>
        public static string CatBehaviourUnknown {
            get {
                return ResourceManager.GetString("CatBehaviourUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volkstuin.
        /// </summary>
        public static string CatchOriginTypeAllotmentGarden {
            get {
                return ResourceManager.GetString("CatchOriginTypeAllotmentGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrijfsterein.
        /// </summary>
        public static string CatchOriginTypeBusinessPark {
            get {
                return ResourceManager.GetString("CatchOriginTypeBusinessPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping.
        /// </summary>
        public static string CatchOriginTypeCamping {
            get {
                return ResourceManager.GetString("CatchOriginTypeCamping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boerderij.
        /// </summary>
        public static string CatchOriginTypeFarm {
            get {
                return ResourceManager.GetString("CatchOriginTypeFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boerderijhuis.
        /// </summary>
        public static string CatchOriginTypeFarmhouse {
            get {
                return ResourceManager.GetString("CatchOriginTypeFarmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natuurgebied.
        /// </summary>
        public static string CatchOriginTypeNatureReserve {
            get {
                return ResourceManager.GetString("CatchOriginTypeNatureReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prive terein.
        /// </summary>
        public static string CatchOriginTypePrivateProperty {
            get {
                return ResourceManager.GetString("CatchOriginTypePrivateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buitengebied.
        /// </summary>
        public static string CatchOriginTypeRuralArea {
            get {
                return ResourceManager.GetString("CatchOriginTypeRuralArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stal.
        /// </summary>
        public static string CatchOriginTypeStable {
            get {
                return ResourceManager.GetString("CatchOriginTypeStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woonwijk.
        /// </summary>
        public static string CatchOriginTypeUrbanArea {
            get {
                return ResourceManager.GetString("CatchOriginTypeUrbanArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eerste fase.
        /// </summary>
        public static string FoodTypeFirstPhase {
            get {
                return ResourceManager.GetString("FoodTypeFirstPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC365.
        /// </summary>
        public static string FoodTypeRc365 {
            get {
                return ResourceManager.GetString("FoodTypeRc365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweede fase.
        /// </summary>
        public static string FoodTypeSecondPhase {
            get {
                return ResourceManager.GetString("FoodTypeSecondPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poes.
        /// </summary>
        public static string GenderMolly {
            get {
                return ResourceManager.GetString("GenderMolly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kater.
        /// </summary>
        public static string GenderTomcat {
            get {
                return ResourceManager.GetString("GenderTomcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onbekend.
        /// </summary>
        public static string GenderUnknown {
            get {
                return ResourceManager.GetString("GenderUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katministratie.
        /// </summary>
        public static string KatministrationTitle {
            get {
                return ResourceManager.GetString("KatministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klontvormend.
        /// </summary>
        public static string LitterGranuleTypeClumping {
            get {
                return ResourceManager.GetString("LitterGranuleTypeClumping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normaal.
        /// </summary>
        public static string LitterGranuleTypeNormal {
            get {
                return ResourceManager.GetString("LitterGranuleTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hout.
        /// </summary>
        public static string LitterGranuleTypeWood {
            get {
                return ResourceManager.GetString("LitterGranuleTypeWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent niet ingelogd. Je kan inloggen door op het gezichtje te klikken.
        ///
        ///Als je nieuw bent moet je jezelf eerst aanmelden door op de plus sign te klikken. 
        ///Nadat je bent aangemeld neem contact op met de beheerder om jou toegang te geven..
        /// </summary>
        public static string LoginBodyText {
            get {
                return ResourceManager.GetString("LoginBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reguliere controle.
        /// </summary>
        public static string MedicalProcedureTypeCheckup {
            get {
                return ResourceManager.GetString("MedicalProcedureTypeCheckup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geneutraliseerd.
        /// </summary>
        public static string MedicalProcedureTypeNeutralize {
            get {
                return ResourceManager.GetString("MedicalProcedureTypeNeutralize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemene notitie.
        /// </summary>
        public static string MedicalProcedureTypeNote {
            get {
                return ResourceManager.GetString("MedicalProcedureTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziek.
        /// </summary>
        public static string MedicalProcedureTypeSickness {
            get {
                return ResourceManager.GetString("MedicalProcedureTypeSickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stronghold.
        /// </summary>
        public static string MedicalProcedureTypeStronghold {
            get {
                return ResourceManager.GetString("MedicalProcedureTypeStronghold", resourceCulture);
            }
        }
    }
}
